name: flame_spatial_grid
description: Spatial partitioning of game field to improve performance of collision detection and rendering
version: 0.9.2
homepage: https://github.com/ASGAlex/flame_spatial_grid

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flame: ^1.23.0
  flame_tiled: ^1.21.2
  meta: ^1.11.0
  isolate_manager: ^5.7.1
  dart_bloom_filter: ^1.0.0
  flat_buffers: ^23.5.26
  vector_math: ^2.1.4
  collection: ^1.19.0
  tiled: ^0.10.2
  xml: ^6.5.0
  js: ^0.7.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: ^2.0.0
  test: ^1.16.0
