name: flame_spatial_grid
description: Spatial partitioning of game field to improve performance of collision detection and rendering
version: 0.8.3
homepage: https://github.com/ASGAlex/flame_spatial_grid

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flame: ^1.8.2
  flame_tiled: ^1.12.0
  meta: ^1.8.0
  collection: any
  tiled: any
  xml: any

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: ^2.0.0
  test: ^1.16.0
