name: flame_spatial_grid
description: Spatial partitioning of game field to improve performance of collision detection and rendering
version: 0.9.0
homepage: https://github.com/ASGAlex/flame_spatial_grid

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flame: ^1.12.0
  flame_tiled: ^1.12.0
  meta: ^1.8.0
  isolate_manager: ^4.1.3
  dart_bloom_filter: ^1.0.0
  flat_buffers: ^23.5.26
  vector_math: ^2.1.4
  collection: ^1.18.0
  tiled: ^0.10.2
  xml: ^6.5.0
  js: ^0.6.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: ^2.0.0
  test: ^1.16.0
