name: flame_spatial_grid
description: Clusterizing game for faster rendering and collision detecting
version: 1.0.0
homepage: https://github.com/ASGAlex/flame_spatial_grid

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flame: ^1.7.3
  flame_tiled: ^1.9.0
  meta: ^1.8.0
  tiled: any

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: ^2.0.0
  test: ^1.16.0
