name: flame_spatial_grid
description: Spatial partitioning of game field to improve performance of collision detection and rendering
version: 0.8.4
homepage: https://github.com/ASGAlex/flame_spatial_grid

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flame: ^1.10.0
  flame_tiled: ^1.12.0
  meta: ^1.8.0
  isolate_manager: ^4.1.3
  dart_bloom_filter: ^1.0.0
  flat_buffers:
    git:
      url: https://github.com/google/flatbuffers.git
      path: dart
  collection: any
  tiled: any
  xml: any

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: ^2.0.0
  test: ^1.16.0
